# Bayesian ML Questions

## Q-1
Let us say we want to find likelihood of happening following events when a fair-coin is flipped 10 times.
$$
R = \{H,T,H,H,T,H,T,T,H,H\}
$$
Probability $p(H=6, T=4)$ in this experiment is given by Binomial probabilities,
$$
p(H=6,T=4|\theta=0.5) = {10\choose6}(0.5)^6(0.5)^4 
$$
But, likelihood of $R$ is given by Bernoulli likelihood,
$$
p(R|\theta=0.5) = (0.5)^6(0.5)^4
$$

Why the $10\choose6$ term is not present in the likelihood?

## Q-2
Let us say you go to casino and find a very simple game of a fair-coin. If it turns out $H$, you win $1\$$ and for $T$, you loose $1\$$. Try to answer the following questions if one plays the game $N$ times, when i) $N=5$ ii) $N=6$.

1. What is the likelihood of winning $N\$$?
1. What is the likelihood of winning $0\$$?

You believed that the coin is fair but you found from your secret sources that $p(H)=0.5, p(H)=0.3$ and $p(H)=0.8$ are all equally possible for any coin. Given that a person won $4\$$ after playing the game $6$ times, what is the probability that he had a coin with $p(H)=0.8$?